server:
  port: 9001
spring:
  application:
    name: cloud-consumer-order9001

eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

